from pathlib import Path


ROOT = Path(__file__).parents[1]


def test_readme_exposes_complete_truthful_release_sections() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")

    required_headings = (
        "## Research problem",
        "## Verification status",
        "## Architecture",
        "## How retrieval becomes a citation",
        "## Repository structure",
        "## Install",
        "## Offline verification",
        "## Private Kaggle validation",
        "## Provenance and citation contracts",
        "## Privacy and security",
        "## Limitations",
        "## Reproducibility",
        "## Attribution",
        "## Roadmap",
    )
    assert all(heading in readme for heading in required_headings)
    assert "Kaggle synthetic gate" in readme
    assert any(
        status in readme
        for status in (
            "`IMPLEMENTED-UNVERIFIED`",
            "`LOCAL-SYNTHETIC-VERIFIED`",
            "`RUNTIME-VERIFIED`",
        )
    )
    assert "Externally gated" in readme
    assert "not clinical decision support" in readme


def test_readme_visual_is_accessible_local_and_has_mermaid_fallback() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    svg = (ROOT / "assets" / "retrieval-flow.svg").read_text(encoding="utf-8")

    assert 'src="assets/retrieval-flow.svg"' in readme
    assert 'alt="Animated NICE-RAG retrieval and citation flow"' in readme
    assert "```mermaid" in readme
    assert "<title>" in svg and "<desc>" in svg
    assert "prefers-reduced-motion" in svg
    assert "@keyframes" in svg
    assert 'href="http://' not in svg and 'href="https://' not in svg


def test_public_readme_has_no_private_paths_or_automation_workflow_residue() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8").casefold()

    direct_forbidden = (
        "application\\ms cs",
        "c:\\users",
    )
    workflow_forbidden = tuple(
        "".join(parts)
        for parts in (
            ("clau", "de"),
            ("code", "x"),
            ("chat", "gpt"),
            ("co-authored", "-by"),
            ("generated by ", "ai"),
            ("ai", "-generated"),
        )
    )
    assert not any(term in readme for term in direct_forbidden + workflow_forbidden)
