from pathlib import Path


ROOT = Path(__file__).parents[1]


def test_readme_exposes_complete_truthful_release_sections() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")

    required_headings = (
        "## Research problem",
        "## Verification status",
        "## Architecture",
        "## How retrieval becomes a citation",
        "## Repository structure",
        "## Install",
        "## Offline verification",
        "## Private Kaggle validation",
        "## Provenance and citation contracts",
        "## Privacy and security",
        "## Limitations",
        "## Reproducibility",
        "## Attribution",
        "## Roadmap",
    )
    assert all(heading in readme for heading in required_headings)
    assert "Kaggle synthetic gate" in readme
    assert any(
        status in readme
        for status in (
            "`IMPLEMENTED-UNVERIFIED`",
            "`LOCAL-SYNTHETIC-VERIFIED`",
            "`RUNTIME-VERIFIED`",
        )
    )
    assert "Externally gated" in readme
    assert "not clinical decision support" in readme


def test_readme_visual_is_accessible_local_and_has_mermaid_fallback() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    svg = (ROOT / "assets" / "retrieval-flow.svg").read_text(encoding="utf-8")

    assert 'src="assets/retrieval-flow.svg"' in readme
    assert 'alt="Animated NICE-RAG retrieval and citation flow"' in readme
    assert "```mermaid" in readme
    assert "<title>" in svg and "<desc>" in svg
    assert "prefers-reduced-motion" in svg
    assert "@keyframes" in svg
    assert 'href="http://' not in svg and 'href="https://' not in svg


def test_public_readme_has_no_private_paths_or_automation_workflow_residue() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8").casefold()

    direct_forbidden = (
        "".join(("appli", "cation", "\\", "ms cs")),
        "".join(("c:", "\\", "users")),
    )
    workflow_forbidden = tuple(
        "".join(parts)
        for parts in (
            ("clau", "de"),
            ("code", "x"),
            ("chat", "gpt"),
            ("co-authored", "-by"),
            ("generated by ", "ai"),
            ("ai", "-generated"),
        )
    )
    assert not any(term in readme for term in direct_forbidden + workflow_forbidden)


def test_readme_separates_verified_open_evidence_from_nice() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")

    assert "`LOCAL-SYNTHETIC-VERIFIED`" in readme
    assert "`OPEN-EVIDENCE-VERIFIED`" in readme
    assert "`NICE-CONTENT-BLOCKED`" in readme
    assert "evidence/open_evidence_acquisition_attempts.json" in readme
    assert "evidence/open_evidence_manifest.json" in readme
    assert "evidence/open_evidence_validation.json" in readme
    assert "python run.py --list-open-sources" in readme
    assert "python run.py --fetch-open-evidence" in readme
    assert "python run.py --validate-open-evidence" in readme
    assert "not NICE guidance" in readme
    assert "PMC5256065" in readme and "PMC9261065" in readme


def test_readme_states_the_future_institutional_gate_without_claiming_affiliation() -> None:
    readme = (ROOT / "README.md").read_text(encoding="utf-8")

    assert "Following anticipated enrolment at University College London in autumn 2026" in readme
    assert "No UCL affiliation, sponsorship, consent, or NICE permission is currently claimed." in readme


def test_failed_acquisition_evidence_is_sanitized_and_not_a_success_claim() -> None:
    evidence_path = ROOT / "evidence" / "open_evidence_acquisition_attempts.json"
    evidence = evidence_path.read_text(encoding="utf-8")

    assert '"status": "PARTIAL"' in evidence
    assert '"open_evidence_verified": false' in evidence
    assert '"raw_xml_committed": false' in evidence
    assert "PMC4410741" in evidence
    assert "PMC9261065" in evidence
    assert "OPEN-EVIDENCE-VERIFIED" not in evidence
    assert "page_content" not in evidence
    assert "article_text" not in evidence
